export default {
    products:[
        {
            _id:'1',
            name: 'Monitor LG',
            category: 'Monitor',
            image: 'images/Monitor-LG.jpg',
            price: 80,
            brand: 'LG',
            rating: 4.5,
            numReviews: 10,
        },
        {
            _id:'2',
            name: 'Gabinete Gamer',
            category: 'Gabinetes',
            image: 'images/Gabinete.webp',
            price: 120,
            brand: 'CompuMax',
            rating: 4.4,
            numReviews: 12,
        },
        {
            _id:'3',
            name: 'Memoria RAM',
            category: 'Memorias RAM',
            image: 'images/Memoria-RAM.webp',
            price: 60,
            brand: 'Dragon',
            rating: 4.3,
            numReviews: 20,
            countINStock: 12,
        },
        {
            _id:'4',
            name: 'Mouse Gamer',
            category: 'Mouse',
            image: 'images/Mouse.webp',
            price: 50,
            brand: 'Dragon',
            rating: 4.5,
            numReviews: 10,
            countINStock: 6,
        },
        {
            _id:'5',
            name: 'Nvidia Gefore RTX 2060',
            category: 'Tarjetas Graficas',
            image: 'images/Tarjeta-Grafica.webp',
            price: 200,
            brand: 'Nvidia Geforce',
            rating: 4.7,
            numReviews: 30,
            countINStock: 11,
        },
        {
            _id:'6',
            name: 'Teclado Gamer',
            category: 'TEclados',
            image: 'images/Teclado.webp',
            price: 55,
            brand: 'Dragon',
            rating: 4.8,
            numReviews: 25,
            countINStock: 6,
        },
    ],
};